[package]
name = "exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0.130"
xml-rs = "0.8.4"
serde = "1.0.130"
lazy_static = "1.4.0"
serde_json = "1.0.68"